# Generated by Django 4.2.5 on 2023-10-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='books',
            index=models.Index(fields=['is_available', 'price'], name='books_books_is_avai_ff31d4_idx'),
        ),
    ]
