# Generated by Django 4.2.5 on 2023-10-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_books_books_is_avai_ff31d4_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': [('can_change_book', 'Can change book')]},
        ),
    ]
